# Generated by Django 4.2 on 2023-05-16 12:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='Sname',
            field=models.CharField(max_length=100, validators=[django.core.validators.MaxLengthValidator(5)]),
        ),
    ]
